#!/usr/bin/env python3
"""Generate the legacy xTB MM-hardness lookup used by the LAMMPS adapter.

The generated header contains only the per-element ``gam`` values needed to
reproduce libxTB's ``mmhardness < 0`` branch.  The canonical xTBloom parameter
JSON remains the source of truth; this script validates dense atomic-number
ordering and writes a deterministic build-tree artifact.
"""

from __future__ import annotations

import argparse
import hashlib
import json
import math
import sys
from pathlib import Path
from typing import Any


def sha256(path: Path) -> str:
    digest = hashlib.sha256()
    with path.open("rb") as handle:
        for chunk in iter(lambda: handle.read(1024 * 1024), b""):
            digest.update(chunk)
    return digest.hexdigest()


def load_hardness(path: Path, expected_name: str) -> list[float]:
    document: dict[str, Any] = json.loads(path.read_text(encoding="utf-8"))
    meta = document.get("meta")
    if not isinstance(meta, dict) or meta.get("name") != expected_name:
        raise ValueError(f"{path} is not the expected {expected_name} parameter export")
    elements = document.get("elements")
    if not isinstance(elements, list) or not elements:
        raise ValueError(f"{path} has no element table")

    values: list[float] = []
    for expected_atomic_number, element in enumerate(elements, start=1):
        if not isinstance(element, dict):
            raise ValueError(f"{path} element {expected_atomic_number} is not an object")
        if element.get("atomic_number") != expected_atomic_number:
            raise ValueError(f"{path} element table is not densely ordered")
        value = element.get("gam")
        if not isinstance(value, (int, float)) or not math.isfinite(value) or value <= 0.0:
            raise ValueError(f"{path} element {expected_atomic_number} has invalid gam")
        values.append(float(value))
    return values


def format_array(name: str, values: list[float]) -> list[str]:
    lines = [f"inline constexpr std::array<double, {len(values)}> {name} = {{"]
    for start in range(0, len(values), 6):
        chunk = ", ".join(repr(value) for value in values[start : start + 6])
        suffix = "," if start + 6 < len(values) else ""
        lines.append(f"    {chunk}{suffix}")
    lines.append("};")
    return lines


def render(
    gfn1_path: Path,
    gfn2_path: Path,
    revision: str,
    expected_gfn1_sha256: str,
    expected_gfn2_sha256: str,
) -> str:
    actual_gfn1_sha256 = sha256(gfn1_path)
    actual_gfn2_sha256 = sha256(gfn2_path)
    if actual_gfn1_sha256 != expected_gfn1_sha256:
        raise ValueError(
            f"GFN1 parameter SHA-256 {actual_gfn1_sha256} does not match "
            f"{expected_gfn1_sha256}"
        )
    if actual_gfn2_sha256 != expected_gfn2_sha256:
        raise ValueError(
            f"GFN2 parameter SHA-256 {actual_gfn2_sha256} does not match "
            f"{expected_gfn2_sha256}"
        )

    gfn1 = load_hardness(gfn1_path, "GFN1-xTB")
    gfn2 = load_hardness(gfn2_path, "GFN2-xTB")
    if len(gfn1) != len(gfn2):
        raise ValueError("GFN1 and GFN2 element ranges differ")

    lines = [
        "#ifndef LAMMPS_DPRC_GENERATED_XTB_HARDNESS_H",
        "#define LAMMPS_DPRC_GENERATED_XTB_HARDNESS_H",
        "",
        "#include <array>",
        "",
        "// Generated by tools/generate_xtb_hardness.py; do not edit.",
        f"// xTBloom revision: {revision}",
        f"// GFN1 JSON SHA-256: {actual_gfn1_sha256}",
        f"// GFN2 JSON SHA-256: {actual_gfn2_sha256}",
        "namespace DPRC::Generated {",
        "",
    ]
    lines.extend(format_array("kGfn1ChemicalHardness", gfn1))
    lines.append("")
    lines.extend(format_array("kGfn2ChemicalHardness", gfn2))
    lines.extend(["", "} // namespace DPRC::Generated", "", "#endif", ""])
    return "\n".join(lines)


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("--gfn1", type=Path, required=True)
    parser.add_argument("--gfn2", type=Path, required=True)
    parser.add_argument("--xtbloom-revision", required=True)
    parser.add_argument("--expected-gfn1-sha256", required=True)
    parser.add_argument("--expected-gfn2-sha256", required=True)
    parser.add_argument("--output", type=Path, required=True)
    parser.add_argument("--check", action="store_true")
    arguments = parser.parse_args()

    try:
        content = render(
            arguments.gfn1,
            arguments.gfn2,
            arguments.xtbloom_revision,
            arguments.expected_gfn1_sha256,
            arguments.expected_gfn2_sha256,
        )
    except (OSError, ValueError, json.JSONDecodeError) as error:
        print(f"hardness generation failed: {error}", file=sys.stderr)
        return 1

    if arguments.check:
        try:
            existing = arguments.output.read_text(encoding="utf-8")
        except OSError as error:
            print(f"hardness check failed: {error}", file=sys.stderr)
            return 1
        if existing != content:
            print(f"hardness check failed: stale generated header {arguments.output}", file=sys.stderr)
            return 1
        return 0

    arguments.output.parent.mkdir(parents=True, exist_ok=True)
    arguments.output.write_text(content, encoding="utf-8")
    return 0


if __name__ == "__main__":
    sys.exit(main())
